Sprint 1
mikhailbys/middle.messenger.praktikum.yandex pull request #1
Opened 2021-10-17 11:22 UTC by mikhailbys

2021-10-17 21:50 UTC, DmitryKhitrin requested changes
Привет, все выглядит не плохо, но пару вещей все же хотелось бы поправить:

- разобраться с `.gitignore`, с таким количеством файлов, все становится очень хаотично);
- вынести подключение стилей в html, так получится оптимальней с точки зрения скорости загрузки интерфейса;
- хорошо бы избавиться от дублирования и разбить стили на атомарные компоненты;
- так же есть несколько комментариев по коду;

Удачи)

2021-10-17 21:50 UTC, DmitryKhitrin commented on .cache/01/6ab05dd01ecdc00747dab9feaa31c6.json
> +{"id":"pages/messages/messages.pug","dependencies":[{"name":"./../profile/profile.pug","dynamic":true,"resolved":"/Users/a1234/WebstormProjects/middle.messenger.praktikum.yandex/src/pages/profile/pro
Эти файлы не надо коммитить в проект, для таких вещей есть специальный файлик `.gitignore`
https://ru.hexlet.io/courses/git_base/lessons/git_gitignore/theory_unit

2021-10-17 21:50 UTC, DmitryKhitrin commented on .gitignore
> +./.cache
`.cache/`

2021-10-17 21:50 UTC, DmitryKhitrin commented on .gitignore
> +./package-lock.json
```suggestion
package-lock.json
```

2021-10-17 21:50 UTC, DmitryKhitrin commented on .gitignore
> +./dist
```suggestion
dist/
```

2021-10-17 21:50 UTC, DmitryKhitrin commented on .gitignore
> +./.idea
```suggestion
.idea
```

2021-10-17 21:50 UTC, DmitryKhitrin commented on .gitignore
> +./package-lock.json
если это файл, то просто пишем имя файла - `package-lock.json`;
если это директория, то пишем ее название со слешем - `dist/`

2021-10-17 21:50 UTC, DmitryKhitrin commented on .idea/middle.messenger.praktikum.yandex.iml
> +</module>
[EOF](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)

2021-10-17 21:50 UTC, DmitryKhitrin commented on .idea/modules.xml
> +</project>
EOF

2021-10-17 21:50 UTC, DmitryKhitrin commented on netlify.toml
> +  publish = "dist"
EOF

2021-10-17 21:50 UTC, DmitryKhitrin commented on src/index.pug
> +html(lang="en")
Текст документа русский

2021-10-17 21:50 UTC, DmitryKhitrin commented on src/index.scss
> +@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap');
Не лучшее решение, описывать все стили в одном файле, в дальнейшем будет очень легко запутаться

2021-10-17 21:50 UTC, DmitryKhitrin commented on src/pages/404error/404error.pug
> +html(lang="en")
`ru`

2021-10-17 21:50 UTC, DmitryKhitrin commented on src/pages/500error/500error.scss
> +button {
Лучше разбить интерфейс на компоненты, тогда индекс файл для каждого пейджа буде просто наборов импортов его составляющих + немного верстки про расположение элементов на странице. В противном же случае, стили для кнопки придется написать n раз, что супер не удобно поддерживать

2021-10-17 21:50 UTC, DmitryKhitrin commented on src/pages/messages/messages.pug
> +            div(class='list-container')
Списки верстаются при помощи тега `<ul>` - элемент списка `<li>`

2021-10-17 21:50 UTC, DmitryKhitrin commented on src/pages/profile/password-change/password-change.pug
> +        script(src='./password-change.js')
EOF

2021-10-17 21:50 UTC, DmitryKhitrin commented on src/pages/profile/profile-change/profile-change.js
> +console.log('Hello index.js!')
EOF

2021-10-17 21:50 UTC, DmitryKhitrin commented on src/pages/profile/profile-change/profile-change.js
> +import '../profile.scss';
Зачем везде импорты из js файла, если можно импортировать стили внутри HTML в head, что бы они сразу загрузились

2021-10-17 21:50 UTC, DmitryKhitrin commented on README.md
> +- `node ./src/server.js` — запуск Express.
Эту команду нужно унести в npm скрипты, никто не будет каждый раз писать путь до boot файла руками:

`server: "node ./src/server.js"` - внутри package.json

2021-10-17 21:50 UTC, DmitryKhitrin commented on README.md
> +- `node ./src/server.js` — запуск Express.
```suggestion
- `npm run server` — запуск Express.
```

2021-10-18 17:06 UTC, mikhailbys commented on .cache/01/6ab05dd01ecdc00747dab9feaa31c6.json
> +{"id":"pages/messages/messages.pug","dependencies":[{"name":"./../profile/profile.pug","dynamic":true,"resolved":"/Users/a1234/WebstormProjects/middle.messenger.praktikum.yandex/src/pages/profile/pro
👍

2021-10-18 17:06 UTC, mikhailbys commented on .gitignore
> +./.cache
👍

2021-10-18 17:07 UTC, mikhailbys commented on .gitignore
> +./package-lock.json
👍

2021-10-18 17:07 UTC, mikhailbys commented on .gitignore
> +./dist
👍

2021-10-18 17:07 UTC, mikhailbys commented on .gitignore
> +./.idea
👍

2021-10-18 17:09 UTC, mikhailbys commented on src/pages/profile/profile-change/profile-change.js
> +import '../profile.scss';
👍

2021-10-18 17:12 UTC, mikhailbys commented on README.md
> +- `node ./src/server.js` — запуск Express.
👍

2021-10-18 17:12 UTC, mikhailbys commented on README.md
> +- `node ./src/server.js` — запуск Express.
👍

2021-10-18 17:16 UTC, mikhailbys commented on src/pages/profile/password-change/password-change.pug
> +        script(src='./password-change.js')
End of file? Не понял, к сожалению, что Вы имели ввиду!
Убрал тут один отступ

2021-10-18 17:16 UTC, mikhailbys commented on src/pages/profile/profile-change/profile-change.js
> +console.log('Hello index.js!')
End of file? Не понял, к сожалению, что Вы имели ввиду!

2021-10-19 08:53 UTC, khitrind approved these changes

2021-11-01 16:05 UTC, merged